name: ecroft_fresh
description: The eCroft Fresh mobile app for produce shopping and delivery.

publish_to: 'none' # This is a private project

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shimmer: ^3.0.0
  lottie: ^2.7.0
  pinput: ^3.0.1
  
  

  # Core Flutter packages
  cupertino_icons: ^1.0.6

  # Firebase
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.7
  cloud_firestore: ^4.15.7

  # Shared Preferences for caching user info
  shared_preferences: ^2.2.2

  # UI helpers
  google_fonts: ^6.2.1
  

  # Optional: geolocation, sign-in, etc.
  geolocator: ^10.1.0
  google_sign_in: ^6.2.1

  # For routing and navigation
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
  - assets/ecroftlogo.png
  - assets/animations/grocery_loader.json
  - assets/animations/onboarding2.json
  - assets/animations/onboarding3.json
  - assets/animations/onboarding1.png
